title: "Mariano Wahlmann's Blog"
url: "https://marianowahlmann.com"
author: "Mariano Wahlmann"
avatar: "/static/avatar.jpg"
email: "mariano.wahlmann_at_gmail.com"
twitter: "https://twitter.com/mwahlmann"
linkedin: "https://www.linkedin.com/in/mwahlmann/"
github: "https://github.com/bluescreen10"
permalink: /:year/:month/:title
paginate_path: /page:num/
plugins: [jekyll-paginate]
paginate: 5
collections:
  links:
    sort_by: date
    output: true