title: "marianowahlmann.com"
url: "https://marianowahlmann.com"
author: "Mariano Wahlmann"
email: "mariano.wahlmann_at_gmail.com"
twitter: "https://twitter.com/mwahlmann"
linkedin: "https://www.linkedin.com/in/mwahlmann/"
github: "https://github.com/bluescreen10"
permalink: /:year/:month/:title